version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: hadolint
          command: |
            docker pull hadolint/hadolint:latest-debian
            docker run --rm -i hadolint/hadolint:latest-debian < Dockerfile

      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up --build -d

      - run:
          name: flake8
          command: |
            docker pull alpine/flake8
            alias flake="docker run -ti --rm -v $(pwd):/apps alpine/flake8:3.5.0"
            flake8

      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop