version: 2
  jobs:
    "hadolint":
      machine:
        image: circleci/classic:edge
        working_directory: ~/repo
      steps:
        - checkout
        - run: docker pull hadolint/hadolint
        - run: hadolint Dockerfile
        - run: hadolint docker-compose.yaml

    "flake8":
      docker:
        image: python:3.9.1
        working_directory: ~/repo
      steps:
        - checkout
        - run: pip3 install flake8
        - run: flake8

workflow:
  version: 2
  build:
    jobs:
      - "hadolint"
      - "flake8"
