name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.29.2'

    - name: docker-compose up
      run: docker-compose up --build -d

    - name: docker-compose stop
      run: docker-compose stop

  flake8_py3:
  
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.2
          architecture: x64
      - name: Checkout
        uses: actions/checkout@master
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8_py3'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  
  hadolint:
  
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2 
    - uses: hadolint/hadolint-action@v1.6.0
      with:
        dockerfile: Dockerfile
  
